robotis_pro7a:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125
  
  # Position Controllers ---------------------------------------
  joint1_position:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 280.0, i: 0.1, d: 2.0}

  joint2_position:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 280.0, i: 0.1, d: 2.0}

  joint3_position:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 190.0, i: 0.1, d: 1.4}

  joint4_position:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 180.0, i: 0.1, d: 1.4}

  joint5_position:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 150.0, i: 0.1, d: 1.4}

  joint6_position:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 150.0, i: 0.1, d: 1.4}

  joint7_position:
    type: effort_controllers/JointPositionController
    joint: joint7
    pid: {p: 150.0, i: 0.1, d: 1.4}