joint1 :   # H54-200-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0
   torque_limit          :  1240
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 399
   velocity_i_gain       : 14

joint2 :   # H54-200-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0
   torque_limit          :  1240
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 399
   velocity_i_gain       : 14

joint3 :   # H54-100-S500-R
   return_delay_time     :  10    # item name : value
   operating_mode        :  3
   shutdown              :  58
   homing_offset         :  -62738   # 45 deg
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 256
   velocity_i_gain       : 16

joint4 :   # H54-100-S500-R
   return_delay_time     :  10    # item name : value
   operating_mode        :  3
   shutdown              :  58
   homing_offset         :  0
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 256
   velocity_i_gain       : 16

joint5  :   # H42-20-S300-R
   return_delay_time     : 10    
   operating_mode        : 3     
   shutdown              : 58    
   homing_offset         : 0     
   torque_limit          : 372
   max_position_limit    : 151900
   min_position_limit    : -151900
   goal_torque           : 372
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 440
   velocity_i_gain       : 40

joint6  :   # H42-20-S300-R
   return_delay_time     : 10    
   operating_mode        : 3     
   shutdown              : 58    
   homing_offset         : 0     
   torque_limit          : 372
   max_position_limit    : 151900
   min_position_limit    : -151900
   goal_torque           : 372
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 440
   velocity_i_gain       : 40

