set(_CATKIN_CURRENT_PACKAGE "vacuum_cmd_msg")
set(vacuum_cmd_msg_VERSION "0.0.0")
set(vacuum_cmd_msg_MAINTAINER "youjun <youjun@todo.todo>")
set(vacuum_cmd_msg_PACKAGE_FORMAT "1")
set(vacuum_cmd_msg_BUILD_DEPENDS "std_msgs" "message_generation")
set(vacuum_cmd_msg_BUILD_EXPORT_DEPENDS "std_msgs" "message_runtime")
set(vacuum_cmd_msg_BUILDTOOL_DEPENDS "catkin")
set(vacuum_cmd_msg_BUILDTOOL_EXPORT_DEPENDS )
set(vacuum_cmd_msg_EXEC_DEPENDS "std_msgs" "message_runtime")
set(vacuum_cmd_msg_RUN_DEPENDS "std_msgs" "message_runtime")
set(vacuum_cmd_msg_TEST_DEPENDS )
set(vacuum_cmd_msg_DOC_DEPENDS )
set(vacuum_cmd_msg_DEPRECATED "")