set(_CATKIN_CURRENT_PACKAGE "robotis_controller_msgs")
set(robotis_controller_msgs_VERSION "0.1.0")
set(robotis_controller_msgs_MAINTAINER "pyo <pyo@robotis.com>")
set(robotis_controller_msgs_PACKAGE_FORMAT "1")
set(robotis_controller_msgs_BUILD_DEPENDS "std_msgs" "sensor_msgs" "message_generation")
set(robotis_controller_msgs_BUILD_EXPORT_DEPENDS "std_msgs" "sensor_msgs" "message_runtime")
set(robotis_controller_msgs_BUILDTOOL_DEPENDS "catkin")
set(robotis_controller_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(robotis_controller_msgs_EXEC_DEPENDS "std_msgs" "sensor_msgs" "message_runtime")
set(robotis_controller_msgs_RUN_DEPENDS "std_msgs" "sensor_msgs" "message_runtime")
set(robotis_controller_msgs_TEST_DEPENDS )
set(robotis_controller_msgs_DOC_DEPENDS )
set(robotis_controller_msgs_DEPRECATED "")