set(_CATKIN_CURRENT_PACKAGE "pro7a_description")
set(pro7a_description_VERSION "0.0.0")
set(pro7a_description_MAINTAINER "youjun <youjun@todo.todo>")
set(pro7a_description_PACKAGE_FORMAT "1")
set(pro7a_description_BUILD_DEPENDS )
set(pro7a_description_BUILD_EXPORT_DEPENDS )
set(pro7a_description_BUILDTOOL_DEPENDS "catkin")
set(pro7a_description_BUILDTOOL_EXPORT_DEPENDS )
set(pro7a_description_EXEC_DEPENDS )
set(pro7a_description_RUN_DEPENDS )
set(pro7a_description_TEST_DEPENDS )
set(pro7a_description_DOC_DEPENDS )
set(pro7a_description_DEPRECATED "")