set(_CATKIN_CURRENT_PACKAGE "manipulator_h")
set(manipulator_h_VERSION "0.2.1")
set(manipulator_h_MAINTAINER "pyo <pyo@robotis.com>")
set(manipulator_h_PACKAGE_FORMAT "1")
set(manipulator_h_BUILD_DEPENDS )
set(manipulator_h_BUILD_EXPORT_DEPENDS "manipulator_h_base_module" "manipulator_h_base_module_msgs" "manipulator_h_bringup" "manipulator_h_description" "manipulator_h_gazebo" "manipulator_h_gui" "manipulator_h_kinematics_dynamics" "manipulator_h_manager")
set(manipulator_h_BUILDTOOL_DEPENDS "catkin")
set(manipulator_h_BUILDTOOL_EXPORT_DEPENDS )
set(manipulator_h_EXEC_DEPENDS "manipulator_h_base_module" "manipulator_h_base_module_msgs" "manipulator_h_bringup" "manipulator_h_description" "manipulator_h_gazebo" "manipulator_h_gui" "manipulator_h_kinematics_dynamics" "manipulator_h_manager")
set(manipulator_h_RUN_DEPENDS "manipulator_h_base_module" "manipulator_h_base_module_msgs" "manipulator_h_bringup" "manipulator_h_description" "manipulator_h_gazebo" "manipulator_h_gui" "manipulator_h_kinematics_dynamics" "manipulator_h_manager")
set(manipulator_h_TEST_DEPENDS )
set(manipulator_h_DOC_DEPENDS )
set(manipulator_h_DEPRECATED "")