set(_CATKIN_CURRENT_PACKAGE "robotis_framework")
set(robotis_framework_VERSION "0.2.0")
set(robotis_framework_MAINTAINER "Pyo <pyo@robotis.com>")
set(robotis_framework_PACKAGE_FORMAT "1")
set(robotis_framework_BUILD_DEPENDS )
set(robotis_framework_BUILD_EXPORT_DEPENDS "robotis_framework_common" "robotis_device" "robotis_controller")
set(robotis_framework_BUILDTOOL_DEPENDS "catkin")
set(robotis_framework_BUILDTOOL_EXPORT_DEPENDS )
set(robotis_framework_EXEC_DEPENDS "robotis_framework_common" "robotis_device" "robotis_controller")
set(robotis_framework_RUN_DEPENDS "robotis_framework_common" "robotis_device" "robotis_controller")
set(robotis_framework_TEST_DEPENDS )
set(robotis_framework_DOC_DEPENDS )
set(robotis_framework_DEPRECATED "")