#goal
string object_name
string[] object_list   # want get closest item
float32[] limit_ary    # limit of  [x_min, x_max, y_min, y_max, z_min, z_max]
---
#result
string object_name   # use for highest item
geometry_msgs/Twist object_pose
geometry_msgs/Vector3 norm
bool success
string error_msg
string[] object_name_ary
---
#feedback
int32 progress
string msg